name: Update datasets

on:
  workflow_dispatch:
  push:
  schedule:
    # At 11:00 by UTC https://crontab.guru
    - cron: '00 11 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip' # caching pip dependencies
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Download and build reports
        run: python main.py
        env:
          TELEGRAM_API_ID: ${{secrets.TELEGRAM_API_ID}}
          TELEGRAM_API_HASH: ${{secrets.TELEGRAM_API_HASH}}
          TELEGRAM_SESSION_STRING: ${{secrets.TELEGRAM_SESSION_STRING}}
          OPENAI_API_KEY: ${{secrets.OPENAI_API_KEY}}
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          default_author: "github_actions"
          message: '🤖 Update datasets'
